name: Release Plugin

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Version
        id: get_version
        run: |
          VERSION="${GITHUB_REF#refs/tags/}"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Zip Plugin
        uses: thedoctor0/zip-release@0.7.5
        with:
          path: ./src/
          filename: wp-github-build-trigger-v${{ steps.get_version.outputs.VERSION }}.zip
          directory: ./

      - name: Read Changelog
        id: read_changelog
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs').promises;
            const changelog = await fs.readFile('./CHANGELOG.md', 'utf8');
            const version = '${{ steps.get_version.outputs.VERSION }}';
            const versionHeader = `## v${version}`;
            const versionStartIndex = changelog.indexOf(versionHeader);

            if (versionStartIndex === -1) {
              core.setOutput('changes', 'No changelog found for this version');
              return
            }

            let versionEndIndex = changelog.indexOf('## v', versionStartIndex + versionHeader.length);
            if (versionEndIndex === -1) {
              versionEndIndex = changelog.length;
            }

            const changes = changelog.slice(versionStartIndex + versionHeader.length, versionEndIndex).trim();
            core.setOutput('changes', changes);

      - name: Upload Asset and Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: wp-github-build-trigger-v${{ steps.get_version.outputs.VERSION }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            Release of WP GitHub Build Trigger v${{ steps.get_version.outputs.VERSION }}

            ## Changes

            ${{ steps.read_changelog.outputs.changes }}
          draft: true
